### PR TITLE
fix: rewrite compile module

### LINKED ISSUE #121: panic: `Option::unwrap()` on a `None` value at core/src/graph/mod.rs:572:66
**Describe the bug**
Panic on calling `synth generate`

**To Reproduce**
1. Schema
users.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "id": {
            "type": "number",
            "subtype": "u64",
            "id": {}
        }
    }
}
```
posts.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "id": {
            "type": "number",
            "subtype": "u64",
            "id": {}
        },
        "user_id": {
            "type": "same_as",
            "ref": "users.content.id"
        }
    }
}
```
images.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "id": {
            "type": "number",
            "subtype": "u64",
            "id": {}
        },
        "post_id": {
            "type": "same_as",
            "ref": "posts.content.id"
        }
    }
}
```
tags.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "image": {
            "type": "same_as",
            "ref": "images.content.id"
        }
    }
}
```
2. See error
```console
$ synth generate ns --collection users
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', synth/core/src/graph/mod.rs:572:66
```

**Expected behavior**
Generated data or an error message explaining what's wrong with the schema.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 21.04

**Additional context**
I was able to reproduce the bug both on the latest release and on master. The schema listed was the most minimal example I was able to find.

### PR DESCRIPTION
**Pull request by brokad**
This rewrites the `compile` module of `core` to remove a bunch of historic hacks. As a result, this handles scenarios with nested references and higher order references better and more consistently.

This closes #121.

# To do's
- [x] Address warnings
- [x] Move the remainder of state relevant things to `state.rs`
- [x] Write tests
    - [x] Detecting cycles on single scope; detecting cycles across scopes
    - [x] Test n-order relations on single scope; test n-order relations across scopes
- [x] Refactor relevant bits of `namespace.rs` to use `Link::Ordered`
- [x] Remove `eprintln`s
- [ ] Enforce the `compile` API contract by making inner Graph variant structs private to `graph` module
- [x] Document compile module: functioning and components

### CODE REVIEW

File: core/src/lib.rs [hunk 1]
```diff
@@ -36,3 +110,21 @@ pub use graph::{Graph, Value};
 
 pub mod compile;
 pub use compile::{Compile, Compiler};
+
+#[cfg(test)]
+pub mod tests {
```
Comment (llogiq) [inline core/src/lib.rs:115]: There's no tests in this module!? If that's intentional, it should really be documented.

**Review by llogiq — APPROVED** [review]
So, this looks mostly OK to me; but while we're at it, I'd like us to document at least the data structures we use. That's make working from there much easier.

**Comment by brokad** [comment]
> So, this looks mostly OK to me; but while we're at it, I'd like us to document at least the data structures we use. That's make working from there much easier.

Thanks for the feedback @llogiq! I have added documenting this to the TODOs of the PR.

File: core/src/compile/mod.rs [hunk 2]
```diff
@@ -507,460 +48,210 @@ impl<'a> NamespaceCompiler<'a> {
...
-                next_scope,
-                own_dependencies.len()
-            );
-
-            let mut foreign_dependencies = Vec::new();
-            for reference in refs.iter() {
-                if !self.vtable.is_built(reference, &next_scope)? {
-                    foreign_dependencies.push(reference.clone());
+            if !next.is_empty() {
+                eprintln!("dependencies not satisfied: {:?}", next);
```
Comment (christoshadjiaslanis) [inline core/src/compile/mod.rs:124]: Perhaps add a comment here about why this is a cycle condition. Explain that by definition a cycle involves a node being a dependency of itself.

File: core/src/compile/mod.rs [hunk 3]
```diff
@@ -507,460 +48,210 @@ impl<'a> NamespaceCompiler<'a> {
...
+                if matches!(self.state.project_mut(address.clone())?.output_mut().waiting(), OutputState::Waiting) {
+                    return Err(anyhow!("cycle detected"));
```
Comment (christoshadjiaslanis) [inline core/src/compile/mod.rs:126]: We can do a little better on the error message here, perhaps give the `address` to give the user a clue about at least one node in the cycle. 

Also let's open an issue to do proper cycle detection (and present it to the user) if we encounter this failure mode.

File: core/src/compile/mod.rs [hunk 4]
```diff
@@ -507,460 +48,210 @@ impl<'a> NamespaceCompiler<'a> {
...
 
+            let state = self.state.project_mut(address.clone())?;
+            let vtable = &mut self.vtable;
+            let mut children = BTreeMap::new();
             let content_compiler = ContentCompiler {
-                scope: next_scope.clone(),
-                cursor: next,
-                drivers: &mut drivers,
-                vtable: &mut self.vtable,
+                scope: address.clone(),
```
Comment (christoshadjiaslanis) [inline core/src/compile/mod.rs:146]: Is `scope` still the right field name here? (Since I think you changed the `Scope` struct to be `Address`.

File: synth/src/sampler.rs [hunk 5]
```diff
@@ -72,42 +93,44 @@ struct NamespaceSampleStrategy {
...
+        let ordered: Vec<_> = model
+            .iter_ordered()
+            .map(|iter| iter.map(|s| s.to_string()).collect())
+            .unwrap_or_else(Vec::new);
+
+        let mut model = model.aggregate();
+
         while generated < self.target {
             let next = model.complete(&mut rng)?;
-            // Here we are building a BTreeMap.
```
Comment (christoshadjiaslanis) [inline synth/src/sampler.rs:82]: I would still add a small comment here because this is kind of opaque datastructure-fu.

File: core/src/compile/link.rs [hunk 6]
```diff
@@ -0,0 +1,316 @@
...
+    {
+        Self(OrderedImpl {
+            is_complete: false,
+            scope: scope.into_iter().collect(),
+            children: children.into_iter().collect(),
+            src
+        })
+    }
+}
+
```
Comment (christoshadjiaslanis) [inline core/src/compile/link.rs:264]: Perhaps add a little documentation explaining taht each variant has to do with being a scope (ordered), a ref from(recorder) and ref to (view).

File: core/src/compile/state.rs [hunk 7]
```diff
@@ -0,0 +1,578 @@
...
+        Self::Link(Link::View(view))
+    }
+
+    pub(super) fn from_recorder(recorder: Recorder<G, Y, R>) -> Self {
+        Self::Link(Link::Recorder(recorder))
+    }
+}
+
+pub type GenArtifact<G: Generator> = Artifact<G, G::Yield, G::Return>;
+
```
Comment (christoshadjiaslanis) [inline core/src/compile/state.rs:211]: I would also lightly document the strate transition here and the 'meaning' of each state :)

**Review by christoshadjiaslanis — COMMENTED** [review]
Thank you for all of this @brokad . I've added some feedback, a minor improvement on some error handling and mostly comments about easy docs that would make a difference.

Thank you!

**Comment by brokad** [comment]
Thank you @christoshadjiaslanis, will address soon :smile:

File: core/src/compile/mod.rs (hunk 3 above)
Comment (brokad) [reply core/src/compile/mod.rs:155]: I am not sure what you mean by "proper cycle detection". To me this code detects all cycles and exactly cycles.

I think what would be useful is a trace of nodes involved in the cycle, so that it is easier to break it.

**Comment by llogiq** [comment]
Great work, @brokad !
