### PR TITLE
fix: number nodes import and schema serde issues

### LINKED ISSUE #145: Allow unbounded `number`s
**Required Functionality**
Currently `number` types can only be `range`, `categorical` (for integers) and `constant` (also some can be `Id`). There is no easy way to specify generating arbitrary numbers

**Proposed Solution**
Consider adding an `unbounded` variant that will generate any valid number of the given type, alternatively make serde use the range default if no argument at all is given.

**Use case**
Simplify the default, allow getting arbitrary numbers without much hassle

### PR DESCRIPTION
**Pull request by brokad**
This 
- Fixes an issue with importing numerical columns from relation datasources where initialization of number ranges to `0..1` together with the `OptionalMergeStrategy` led to incorrect import schemas.
- Makes `low, high, step` in `range` optional. At compile-time, the option is unwrapped_or replaced by the min/max/one of the corresponding subtype (for integer subtypes) or `0.1` and `1.` (for float subtypes).
- Tweaks the OptionalMergeStrategy to mutate `None -> Some(value)` as soon as a number value is merged and thereafter proceeds as before.
- Cleans up some of the macro code around numbers for readability and reduce redundancies.
- Removes `s_override` module
- Better error reporting on invalid ranges and replaces a panic surface around `rand` with an error report and a suggestion
- Adds boolean parameters `include_high` and `include_low` to `range` that let the user decide whether to include the bounds in the range

All these changes should be backward compatible.

This also adds a default behavior for number nodes whereby
```json
{
  "type": "number",
  "subtype": "u64"
}
```
is interpreted as a `"range": {}`, i.e. a generator of numbers between `u64::MIN` and `u64::MAX`.

## TODOs
- [x] Fix overflow issue with our implementation of UniformRangeStep (due to the fact we use the same impl for integers and floats)
- [x] Document the new behavior of `"range"` and the default for numbers.
- [x] (Maybe) correct the testing harnesses which may have been written using the incorrect init/merge

This closes #145.

### CODE REVIEW

File: core/src/graph/mod.rs [hunk 1]
```diff
@@ -744,7 +744,11 @@ pub mod tests {
                             "generator": "safe_email"
                         }
                     },
-                    "num_logins_again": "@users.content.num_logins"
+                    "num_logins_again": "@users.content.num_logins",
+                    "a_large_number": {
+                        "type": "number",
+                        "range": {}
```
Comment (llogiq) [inline core/src/graph/mod.rs:750]: what happens if the user completely omits the `"range"` entry?

Comment (brokad) [reply core/src/graph/mod.rs:750]: It is interpreted as `"range": {}`, see the [notes on the PR](https://github.com/getsynth/synth/pull/146#issue-996021289).

File: core/src/graph/number.rs [hunk 2]
```diff
@@ -1,51 +1,291 @@
...
+                    (Bound::Excluded(low), Bound::Excluded(high)) => *low + 1 >= *high,
+                    _ => false
+                }
+            }
+        }
+
+        impl SampleRange<$target> for AnyRange<$target> {
+            fn sample_single<R: rand::RngCore + ?Sized>(self, rng: &mut R) -> $target {
+                let low = match self.low {
+                    Bound::Unbounded => panic!("cannot sample {} range unbounded on the left", stringify!($target)),
```
Comment (christoshadjiaslanis) [inline core/src/graph/number.rs:34]: Why not `$target::MIN()` for Unbounded on the left?

File: core/src/graph/number.rs [hunk 3]
```diff
@@ -1,51 +1,291 @@
...
+///
+/// In particular when `$target == $larger == $unsigned` is an unsigned integer type these are
+/// no-ops.
+macro_rules! standard_int_range_step_impl {
+    { $target:ty, $larger:ty, $unsigned:ty } => {
+        impl StandardIntRangeStep<$unsigned, $larger> {
+            pub fn try_from_range(range_step: RangeStep<$target>) -> anyhow::Result<Self> {
+                let low = range_step.low.unwrap_or(<$target>::MIN);
+                let high = range_step.high.unwrap_or(<$target>::MAX);
+                if low > high {
```
Comment (christoshadjiaslanis) [inline core/src/graph/number.rs:171]: Should this not be `low >= high` since `high` is open?

File: core/src/graph/number.rs [hunk 4]
```diff
@@ -1,51 +1,291 @@
...
+                    return Err(anyhow!("integer range cannot have 'low'={} > 'high'={}", low, high))
+                }
+
+                let delta = ((high as $larger) - (low as $larger)) as $unsigned;
+
+                let step_unchecked = range_step.step.unwrap_or(1);
+                if step_unchecked <= 0 {
+                    return Err(anyhow!("integer range 'step'={} is invalid, use a positive value instead", step_unchecked))
+                }
+
```
Comment (christoshadjiaslanis) [inline core/src/graph/number.rs:181]: We could add 

```rust
if step_unchecked == 0 {
    return Err(anyhow!("integer range step 0 is invalid, use the Number::Constant generator instead."))
}
```

Comment (christoshadjiaslanis) [reply core/src/graph/number.rs:181]: Or something along those lines.

File: core/src/graph/number.rs [hunk 5]
```diff
@@ -119,7 +359,7 @@ impl<N> Generator for Incrementing<N>
                 } else {
                     GeneratorState::Complete(Err(failed_crate!(
                         target: Release,
-                        "incrementing generator overflowed: try using a larger type"
+                        "incrementing generator overflowed: try specifying the \'subtype\' parameter with a larger numerical primitive (e.g. u64)"
```
Comment (christoshadjiaslanis) [inline core/src/graph/number.rs:362]: Nice touch :)

File: core/src/schema/content/number.rs [hunk 6]
```diff
@@ -66,224 +66,266 @@ macro_rules! number_content {
...
+                                Ok(Self::$def())
+                            } else {
+                                let inner = number_content::$as::deserialize(v).map_err(D::Error::custom)?;
+                                Ok(NumberContent::$as(inner))
+                            }
+                        }
+                        else
+                    )*
+                        {
+                            //TODO: generate static array with variant names and pass it to
```
Comment (christoshadjiaslanis) [inline core/src/schema/content/number.rs:142]: TODO here

File: core/src/schema/content/number.rs [hunk 7]
```diff
@@ -66,224 +66,266 @@ macro_rules! number_content {
...
-    pub low: N,
-    pub high: N,
-    pub step: N,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub low: Option<N>,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub high: Option<N>,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    pub step: Option<N>,
+    #[serde(skip_serializing_if = "std::clone::Clone::clone")]
```
Comment (christoshadjiaslanis) [inline core/src/schema/content/number.rs:220]: What is happening here? Why skip serializing if `clone`?

File: core/src/schema/mod.rs [hunk 8]
```diff
@@ -28,7 +28,6 @@ pub mod inference;
 pub use inference::{MergeStrategy, OptionalMergeStrategy, ValueMergeStrategy};
 
 pub mod optionalise;
-pub mod s_override;
```
Comment (christoshadjiaslanis) [inline core/src/schema/mod.rs:31]: Nice ;)

File: docs/docs/content/number.md [hunk 9]
```diff
@@ -22,13 +22,81 @@ the best value based on the value of other parameters. But it may be necessary
 to set it manually in situations where the data sink only accepts certain
 widths (e.g. postgres).
 
+### Defaults
+
+If no variant (such as `range`, `constant`, etc.) is specified, `number`
```
Comment (christoshadjiaslanis) [inline docs/docs/content/number.md:27]: This piece of doc doesn't really have continuity.

`defaults to: - For integer subtypes...: generating one of the...`

Basically I don't follow what is happening here :joy:

**Review by christoshadjiaslanis — COMMENTED** [review]
Really good stuff @brokad . I left some comments which are minor. 

Thank you for taking the liberty also to cleanup `s_override`. Much needed!

File: core/src/graph/number.rs (hunk 2 above)
Comment (brokad) [reply core/src/graph/number.rs:34]: Because that is not unbounded, that’s bounded inclusive. The `rand` API this wraps around follows the same logic.

File: core/src/schema/content/number.rs (hunk 6 above)
Comment (brokad) [reply core/src/schema/content/number.rs:142]: An item left over from before this PR and got added to the diff as a result of the refactor. I think the idea was to make the serde error better, but we eventually worked around it. I will remove it.

File: core/src/schema/content/number.rs (hunk 7 above)
Comment (brokad) [reply core/src/schema/content/number.rs:220]: This is equivalent to testing the value to be true.

File: docs/docs/content/number.md (hunk 9 above)
Comment (brokad) [reply docs/docs/content/number.md:27]: @christoshadjiaslanis can you take a look at latest and see if this is satisfactory to you?
